### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by AbelLykens** [br0xen/boltbrowser#45]
Hey, I am using boltbrowser trying to fix a problem I have with the lnd software, which uses a bolt DB.

I need to delete some records in a 120k long list. Scrolling takes a bit, I estimate it will take 30+ hours of scrolling to get to the record.

Being able to jump to a record starting with XX, or searching, would be the absolute best option. 

Please consider, it would help a lot. Thank you!

https://github.com/guggero/chantools/issues/22#issuecomment-890340412

**Comment by br0xen** [comment]
Yikes, yeah, that doesn't sound like a good time.

Unfortunately I'm not at a point that I can dump a bunch of time into this project right now... 
I know there is a 'filter' command that was added at some point (just hit `/`), I honestly haven't really used it much and it's been maybe two years since I've done anything with boltbrowser (other than minor bug fixes) or even a boltdb. Give it a try, maybe it'll work.

Another option would be to use something like
https://github.com/magisterquis/dumpbolt

Then you could just use a text editor.

**Comment by AbelLykens** [comment]
Thank you @br0xen . Good hints. The fork I was working on does not have that, but will try to get it in.

https://github.com/guggero/chantools/issues/22#issuecomment-891010166

The dumpbolt seems to go one way; not sure (how) I can reconstrurt a boltdb from the (cleaned up) text. 

Thanks for your time!

**Comment by AbelLykens** [comment]
Fixed using new code by @guggero :). Thanks for your time and responses  @br0xen , much appreciated!
